### PR TITLE
fix: fix tabs cursor

### PR DESCRIPTION
**Pull request by th3rius**
Add cursor: pointer to the entire tab

Gravação de tela de 09-05-2022 08 56 46

### CODE REVIEW

**Review by alanneves — APPROVED** [review]
LGTM (u need to bump the version)

**Review by mickaelnn — DISMISSED** [review]
LGTM

**Review by alanneves — APPROVED** [review]
LGTM

**Review by mickaelnn — APPROVED** [review]
LGTM

**Pull request merged**
