### PR TITLE
[CO-728] Feature/improved lines on WorkflowGraph

### PR DESCRIPTION
**Pull request by ixpd**
### Description
In this pr, was improved the lines on WorkflowGraph

### Jira Card
[CO-728 - Linhas do WorkflowGraph estão apresentando erros](https://amctextil.atlassian.net/jira/software/c/projects/CO/boards/1?modal=detail&selectedIssue=CO-728)

### Screenshots
Screenshot_31

### CODE REVIEW

**Review by marcosalves-bitg — COMMENTED** [review]
LGTM

**Review by marcosalves-bitg — DISMISSED** [review]
LGTM, é lindo. Muito bonito

**Review by GabrielPedrotti — DISMISSED** [review]
QBIXO

**Review by marcosalves-bitg — APPROVED** [review]
QBIXO²

**Review by GabrielPedrotti — DISMISSED** [review]
QBIXO³

**Review by planivic1 — APPROVED** [review]
LGTM

**Review by GabrielPedrotti — APPROVED** [review]
QBIXO²²

**Pull request merged**
